platform :ios, '8.0'
target "DYZB" do
    pod 'AFNetworking', '~> 3.1.0'
    pod 'Masonry', '~> 1.0.1'
    pod 'MJExtension', '~> 3.0.13'
    pod 'SDWebImage', '~> 3.8.1'
    pod 'FLEX', '~> 2.0', :configurations => ['Debug']
end
